JOB_CREATED = "CREATED"
JOB_PLANNED = "PLANNED"
JOB_RUNNING = "RUNNING"
JOB_GENERATING_DOCUMENT = "GENERATING_DOCUMENT"
JOB_COMPLETED = "COMPLETED"
JOB_FAILED = "FAILED"
MAX_RETRIES = 3

STEP_PENDING = "pending"
STEP_COMPLETED = "completed"
STEP_FAILED = "failed"